[project]
name = "cold-email-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=0.6.3",
    "langchain-community>=0.3.18",
    "langchain[groq]>=0.3.19",
    "streamlit>=1.42.2",
]
